services:
  notifydev-api:
    command: sh -c "npm install && npx prisma generate && npx prisma migrate deploy && npm run dev"
    environment:
      - NODE_ENV=development
    env_file:
      - ./notifydev-api/.env.local
    volumes:
      - ./notifydev-api:/app
      - /app/node_modules

  notifydev-web:
    command: 'sh -c "npm install && npm run dev"'
    environment:
      - NODE_ENV=development
    volumes:
      - ./notifydev-web:/app
      - /app/node_modules

  worker:
    command: sh -c "npm install && npx prisma generate && npx nodemon --watch src/worker src/worker/worker.js"
    env_file:
      - ./notifydev-api/.env.local
    volumes:
      - ./notifydev-api:/app
      - /app/node_modules
